### ISSUE TITLE
Copied Pages should add canonical tags

### ISSUE THREAD

**Issue by munnster** [PiranhaCMS/Piranha#354]
Hi,

Hoping to go live with our first Piranha site this Friday :)

One missing feature that would be good for SEO is to automatically add the Canonical link tag to the head section for copied pages

Thanks

Ali

**Comment by hades200082** [comment]
+1

All pages should have a canonical tag to be safe.

Canonical tags should take account of the prefixless permalinks setting.

Additionally, the homepage for a given site is a special case that should have it's canonical set to simply the root of the site.

I've tried building something in layout from what we already have for this...

```csharp
<link rel="canonical" href="@(Request.IsSecureConnection ? "https://" : "http://")@Request.Url.Host@UI.Permalink((Request.RawUrl == "/" ? "" : Request.RawUrl))" />
```

But this doesn't seem to take account of the prefixless setting.  The `@UI.Permalink()` renders the prefix regardless.

**Comment by tidyui** [comment]
Let's add this into the next version and maybe adding a config setting for it.

**Comment by hades200082** [comment]
Any way I can work around it in the current version?

**Comment by tidyui** [comment]
I'm currently testing 2.2.5, as soon as it's released I'll look at the code you provided and how to achieve it in the current version!

**Comment by tidyui** [comment]
Well @hades200082 I took a look at this issue, and there's some challenges with implementing it without database changes.

Let's say you have two sites:

    http://mainsite.com
    http://productsite.com

On the product site you're displaying a page from the main site, so you want to add a canonical tag for it. The problem here is that host names are resolved dynamically, i.e when surfing `productsite.com` there's no way of knowing for sure the **hostname** for `mainsite.com`.

You add hostnames for your SiteTrees, but quite often you add several hostnames, for development and production for easy deployment and maintenance. For example, the productsite could have the following hostnames:

    productsite.com,products.local,products.devserver

As in issue #391 we would need a new field (or perhaps config setting) with the primary hostname for each site.

Or have I misunderstood the issue @hades200082 @bapti @munnster ?

**Comment by hades200082** [comment]
The main issue is that every page should have a canonical URL pointing to the "one true URL" for that page on the current site.

The other issue is where you have taken content from another site verbatim, some people set the canonical URL for that content to the URL on the other site in an attempt to prevent Google from penalising them for duplicate content... in practice Google ignores canonicals that are not for the same domain.

The canonical tag is simply to prevent Google from indexing multiple URL's for the same page.

A simple example is the difference between "http://www.domain.com" and "http://domain.com" versions.

Our website for example uses "https://domain.com" format ... we currently have code and redirects in place to ensure that everyone uses that version. 

The problem grows the bigger the site gets as you find yourself having to create redirects and rewrite rules for more and more cases.  The simpler solution is to allow the other URL's to load the page but have a canonical tag in the head telling Google which one to actually index.

Another example of canonical usage would be where you have querystrings in use in the URL but where those querystrings don't affect the page content ... in that case the canonical would be the version without the querystrings, otherwise Google would index every querystring version separately.


Likewise, on a slightly tangential subject, rel="prev" and rel="next" links should be present or sequenced pages.  I.e. where you paginate something, like a list of posts for example, the rel next and prev links tell Google and other crawlers that the pages are part of a related sequence.
