### ISSUE TITLE
Show posts for a specific category

### ISSUE THREAD

**Issue by erwin-beckers** [PiranhaCMS/Piranha#393]
Could you give me a example how to i can get all posts for a specific category ?
I've looked into the documentation but could  not find how to do this.

**Comment by dirodrigues** [comment]
Something like this should work:
````
foreach (var myPost in myPosts)
            {
myPost
            .Categories
            .Where(category => category.Name == "category name")
            .Select(category => myPost);
}
````
D

**Comment by tidyui** [comment]
Sorry for an **extremely** late answer, I missed your issue when you created it but thanks to @dirodrigues comment it popped up again :)

Back in the dawn of time (Piranha CMS time that is) some shortcuts were made to get the initial version up and running. One of these shortcuts were to skip many-to-many connection tables in the database and just put them in a generic relation table (mainly because the database was handwritten and not generated).

This said, the categories for a certain post is stored in a the 'relation' table in the database and has the type 'POSTCATEGORY'. The field 'relation_data_id' will contain the **post id** and the field 'relation_related_id' will contain the **category id**. If you know the `id` of your category, the easiest way to achieve a database-search for posts is to first get the post id's:

    using Piranha.Models;

    var ids = Relation.GetByTypeAndRelatedId(Relation.RelationType.POSTCATEGORY, categoryId);

Then just load the posts matching each id in the result. If you use the internal mapper instead of Entity Framework all calls for Id will be **cached in memory**.

    var posts = new List<Piranha.Models.Post>();

    foreach (var id in ids) {
      var post = Piranha.Models.Post.GetSingle(id);
      if (post != null)
        posts.Add(post);
    }

Hope this helps!

Regards

Håkan
