### ISSUE TITLE
Posts get shared on all sites ?

### ISSUE THREAD

**Issue by erwin-beckers** [PiranhaCMS/Piranha#445]
Hi there, 
I want to create multiple sites  
Adding different sites in the manager interface works
When going to manager/content/pages i can select a site and create separate pages for each site

However when going to manager/content/posts, i cannot select a site ??
it seems that all posts gets shared on all sites ?? 
I really would like each sites to have separate posts, just like pages
Is this something that PiranhaCMS already supports ? or is this not possible yet ?

Regards

Erwin

**Comment by tidyui** [comment]
Hi there! This is actually by design. Piranha CMS was never intended to be used as a multi-tenant system, all data is shared between sites except the site structures. The same page can actually exist in several sites.

Instead sites was intended to be used for when creating marketing & campaign sites for a single customer.

I would say create different post types and use this as a filter if you for example would like different news-items for different sites.

However, if you're looking for full multi tenant support I'd suggest looking into the other platforms supporting this, for example orchard.

Regards.
