### ISSUE TITLE
Oracle database compatibility

### ISSUE THREAD

**Issue by hmny** [PiranhaCMS/Piranha#465]
Hey Håkan,
What kind of databases does it support? We use Oracle using `ODP.NET` in our projects and wondering if it's compatible with Piranha

**Comment by tidyui** [comment]
Hi there! The code has only been verified and tested against the different versions of SqlServer (LocalDb, SqlExpress, SqlServer 2008, SqlServer 2012). Since it's a rather lightweight framework there has never been any requests of questions about running it on Oracle. 

One thing that might be a problem is creating the actual database as this is done through manual SQL-scripts (https://github.com/PiranhaCMS/Piranha/blob/master/Core/Piranha/Data/Scripts/Create.sql) which uses column types that are specific to SQL Server. On the other hand it might run just perfectly when the database has been created.

The long term plan is to move schema creation and query generation over to Entity Framework which will then result in Piranha supporting whatever database Entity Framework supports.

Regards
