### ISSUE TITLE
Piranha Tutorial please

### ISSUE THREAD

**Issue by PollyAnna44** [PiranhaCMS/Piranha#466]
Hi, I have created a new project with a SQL DB.  It then created an user for me.  I then went to the Log in page and entered the user and password and all it does is stay on the log in page and do nothing else.  If I enter a false user Id and password then it tells me so.  Therefore the user id and password is correct.  Do you have any tutorials that would give me an idea of how to get started.  I have been to your web site and can't even get on to the Manager page as I am stuck on the login page. A You tube tutorial would be appreciated and perhaps some sample code.
Thank you for your help, 

Regards, Polly

**Comment by serrnovik** [comment]
I've also hit this issue when started to dig into. The issue in my case was (and partially still is) is conflict between Piranha Forms login and MVC users module modules -> Microsoft.ApplicationInsights.Web.ApplicationInsightsHttpModule. In order to get to managing console you have to remove this part. 

There is another issue how to combine two of those. As far as I understand the only way for now is to have two applications. One for managing and one for end users. I've asked questions about it but have not found other answers yet. 

Tutorial about creating custom pages and probably ready to use code example would be great by the way.

**Comment by NelsonLamprecht** [comment]
PollyAnna44, PiranhaCMS looks nice but I did the same thing. Brand new project, followed the steps to create a new project and got the login form that would validate credentials, (I think) but go nowhere http://*/manage was the url I used...Did you get anywhere?
