### ISSUE TITLE
Preview not working

### ISSUE THREAD

**Issue by Silverduck777** [PiranhaCMS/Piranha#472]
Hello,
I would like to use the PiranhaCMS framework.
So I made a test program.
I started from a Empty MVC project (VB 2013)
I loaded PiranhaCMS.MVC with Nuget.

I changed the connection string and made a db.
When I first started the project, I made a new user, but when I tried to login on the next screen, I had a problem, I reveiced a null expection. I restarted the project and I could log in.

I can see your inferface to created pages, ...
I can make pages but when I try the preview, I see following error

The partial view 'Partial/Menu' was not found or no view engine supports the searched locations. The following locations were searched:
~/Views/page/Partial/Menu.cshtml
~/Views/page/Partial/Menu.vbhtml
~/Views/Shared/Partial/Menu.cshtml
~/Views/Shared/Partial/Menu.vbhtml
~/Areas/Manager/Views/Extensions/Partial/Menu.cshtml
~/Views/page/Partial/Menu.aspx
~/Views/page/Partial/Menu.ascx
~/Views/Shared/Partial/Menu.aspx
~/Views/Shared/Partial/Menu.ascx

Must I still do something extra, to make it work?

Kind Regards Kris

**Comment by tidyui** [comment]
Hi there!

The first issue with the **null exception** after a clean install is reported and will be fixed with the next release, see #417 for details.

If the second error occurs when you are accessing the public site my guess is that Visual Studio must have **scaffolded** files over the default files in the project. The reason for this is that the template layout doesn't have a partial view call `Menu`, for reference see:

https://github.com/PiranhaCMS/Piranha/blob/master/Templates/TemplateSite.Mvc/Views/Shared/_Layout.cshtml

**Comment by Silverduck777** [comment]
Thanks for the fast feedback. I will check it out.

**Comment by tidyui** [comment]
This question was brought to my attention in issue #475. Your problem is that the NuGet package `Piranha.Mvc` only contains the binary packages, it doesn't provide any default **controllers** or **views** to handle requests to the front end web. I'll paste the answer from the other issue here as well

---

So, I've created a new repo here where I've added an MVC example for Mixed Mode. In my example I've assumed that you've added the package piranha.mvc from NuGet.

https://github.com/PiranhaCMS/Examples

I followed the guidlines from Adding Piranha CMS to an existing application at http://piranhacms.org/docs/introduction/getting-started except for letting passiveMode be false.

For me the setup works perfectly exept for the fact that CMS generated pages doesn't work. The reason for this is that the template package piranhacmsmvc bundles two controllers and views for rendering CMS content. These are of course not present in the lib setup of piranha.mvc.

In my example repo I've added the default controllers & views for pages & posts.
