### ISSUE TITLE
Property Naming and Expando Objects

### ISSUE THREAD

**Issue by PhillipHamlyn** [PiranhaCMS/Piranha#474]
I can name a Property with spaces in the name, in order to make it user-readable, but the Expando object generated also have spaces in the property name, and this makes it unusable in Razor. 

Request that the Expando object replaces spaces with underscore to maintain the user-readable format of the property, and make it usable in Razor.

**Comment by tidyui** [comment]
Or rather, let's add some verification to the manager interface & Page Type import to signal when a property value is incorrect. In general, the properties feature is rather old and hasn't changed since the initial version four years ago.

In the long run a complete overhaul of the feature would be appropriate :)

Regards

**Comment by PhillipHamlyn** [comment]
I'm not entirely in agreement - it seems reasonable to name a Property using spaces - they are user-oriented. The only problem surfaces when trying to program against them. I see that you manufacture Permalinks using a space-replacement algorithm - I'd be happier with that than forcing the user to omit spaces from their property name...

**Comment by tidyui** [comment]
Good point!
