### ISSUE TITLE
Best Practise ? How Much Managed Content ?

### ISSUE THREAD

**Issue by PhillipHamlyn** [PiranhaCMS/Piranha#483]
When building Piranha into my existing application I have a decision to make for each page type as to how much content to delegate to Piranha. What is the best practise here ? For instance, should the text on my Form Buttons be delegated to Piranha ? What about individual field labels ? What level should be delegated to the app Resources and how much to the CMS ?

Its my first foray into CMS so I don't know how deep to go :0)

**Comment by tidyui** [comment]
I would say, only add content to the Page types that **content managers** are supposed to add. Labels for forms, buttons and so on should be kept in the app Resources **or** in a key value storage in the database if the customer demands control over them. This is a better approach has labels are usually reused throughout the site and this would mean changing them in a single place, rather than on all pages using that label.

If you need to keep your resource dictionary in the database you should create this in your own `DbContext` and you could then add a custom manager view for it so they can administrate it from within the Piranha CMS manager. You can find information about this approach here:

http://piranhacms.org/docs/extend/custom-entities
http://piranhacms.org/docs/extend/manager-menu

Regards
