### ISSUE TITLE
support for ssl

### ISSUE THREAD

**Issue by theslyone** [PiranhaCMS/Piranha#490]
I've set up my application with multiple sub domain sites as required, everything works fine. But i have just added a redirect from all http request to https in my web.config file and suddenly it doesn't seem to hit the application anymore. Any suggestions please, it's really pressing.

Thanks alot.

**Comment by tidyui** [comment]
That's quite odd since all internal linking is relative to the current scheme/domain the application is running on. You can for example try out the official Piranha CMS site in https and there's no modifications done for it:

https://piranhacms.org

Exactly how have you setup https in web.config and in your IIS, can you confirm that something other than your Piranha pages is actually responding over https?

**Comment by theslyone** [comment]
The problem was indeed from my web hosting provider. Thank you @tidyui :)

**Comment by tidyui** [comment]
No problem!
