### ISSUE TITLE
NuGet Package Updates  break site

### ISSUE THREAD

**Issue by glerler** [PiranhaCMS/Piranha#547]
Updated packages in the project.  I think I had Piranha2.2.2 and updated.  Ran into issues with mapping.  Backed off a version.   the packages made changes to my webconfig and everything went to hell.  Multiple sections, overwrote the connection strings I had.   IIS gave me a 500 error.   Arghhh!!!!  Now I get a unable to load request.  I dont see a reference now for the  Piranha assembly in the webconfig.

**Comment by glerler** [comment]
More info;
I am getting an initialization exception.  
[TypeInitializationException: The type initializer for 'Piranha.Application' threw an exception.]
   Piranha.WebPages.WebPiranha.BeginRequest(HttpContext context) +2344
   System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +142
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +92

**Comment by tidyui** [comment]
The web.config issue is unfortunately by design in NuGet. Since the `web.config.transform` is included in the base-package (PiranhaCMSMvc), every time you update it the values you've changed in your local web.config gets duplicates.

The only way to get around it is to use project templates for the base projects instead of NuGet-packages, and that has it's downsides as well in terms of maintenance and distribution.

The error message doesn't really give much to go on, is that really the entire stack trace? There's a lot of initializing going on when the application is created.

Regards

**Comment by glerler** [comment]
Got things going.
Rolled back git to the commit I did before I started updating the packages.  That got me at least back to where I started.  Started updating with commits in between.
Jquery, bootstrap and  others all updated all updated w/o issue
Then into the MVC & Piranha package updates.
Looks like you did some architectural changes with Piranha. Numerous webconfig changes.

  1.  I ended up with duplicate entries.
  2.  Overwrote my connection strings
  3.  Wanted to overwrite the webconfig in sub directories.
After making some manual edits in the config the site loaded correctly.  I am at 2.2.3 .  haven’t brought it up to 2.2.7 yet.
A few ?

  1.  Where does the AutoMapper package fit in? I don’t have it now but  It was installed before I rolled it back.  I don’t remember working with it before.
  2.  Should I update the Piranha template package???  It wants to overwrite files.



Once again thanks for your response.



Glenn
