### ISSUE TITLE
Properties are not removed from Post Model after being deleted from a POST TYPE 

### ISSUE THREAD

**Issue by samuelmaxton** [PiranhaCMS/Piranha#551]
I see that Issues #14 and #15 are similar to this issue, but apparently this problem still exists for Properties attached to POST TYPES. 

Please help!

**Comment by tidyui** [comment]
Properties truly are a quick implementation from 2011 that has some limitations. The property info on the Post Type is just stored as a JSON-serialized array, thus no foreign keys to the actual property values exists so no cascading is applied when the property is removed from the post type.

I went through the code and like you see, there doesn't appear to be any removal of the orphan property values either when the post type or the post is saved.

Until it's fixed in the NuGet-packages this could be implemented by adding some code into the hook for saving a post, cleaning away old properties.

    Hooks.Manager.PostEditModelLoaded += (controller, menu, model) => {
        // Delete properties for the post that does not exists for the post type
    } ;

Best regards

Håkan

**Comment by samuelmaxton** [comment]
Thanks! But wouldn't this be the more logical Hook to use? Or is there a reason why this wouldn't work?

`Hooks.Manager.PostEditModelBeforeSave += (controller, menu, model) => {
    // Delete properties for the post that does not exists for the post type
} ;`

**Comment by samuelmaxton** [comment]
Thanks @tidyui ! Where is the code that grabs the Properties connected to a Post on page load?

**Comment by tidyui** [comment]
Well there is a **key**, but the same table is used both for page & post properties, so there's no real **foreign key** pointing to the post table :)

**Comment by samuelmaxton** [comment]
I assume "property_parent_id" in the Properties table is what your referring to? But I'm unable to find a connection between that column and Posts or Post Templates.
