### ISSUE TITLE
Adding Piranha 5.0 To an Existing DOT.NET Core 2.1 App

### ISSUE THREAD

**Issue by webzest** [PiranhaCMS/Piranha#568]
Hi,

I have a working DOT.NET Core 2.1 App with --auth individual and an Existing SQL Server.  I installed the latest Piranha Stable Nuget, version 5 without errors and would like to start a blog from my existing App.

How do I proceed with the integration from that installation?

Do you have instructions that I can follow to integrate your wonderful Piranha App with my App and avoid having to build a new separate BLOG?

Thank you for your support.

**Comment by tidyui** [comment]
Hi there! The reason you're not finding any info here is because you're in the wrong place :) This is the repository for the old legacy version of Piranha (2.x). The current version can be found at:

[https://github.com/piranhacms/piranha.core](https://github.com/piranhacms/piranha.core)

Please re-open the issue in the correct repository, because then others can find the response as well, instead of me replying here!
